// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Thu May 30 13:07:18 2019

LED_counter LED_counter_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.reset(reset_sig) ,	// input  reset_sig
	.switch(switch_sig) ,	// input  switch_sig
	.leda3(leda3_sig) ,	// output [7:0] leda3_sig
	.leda2(leda2_sig) ,	// output [7:0] leda2_sig
	.leda1(leda1_sig) ,	// output [7:0] leda1_sig
	.leda0(leda0_sig) ,	// output [7:0] leda0_sig
	.select3(select3_sig) ,	// output  select3_sig
	.select2(select2_sig) ,	// output  select2_sig
	.select1(select1_sig) ,	// output  select1_sig
	.select0(select0_sig) 	// output  select0_sig
);

